import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, readdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { request } from 'node:http';
import { DemoSession } from '../spikes/demonstrator/session.mjs';
import { ReleaseRuntime } from '../spikes/release/runtime.mjs';
import { startDemo } from '../spikes/demonstrator/server.mjs';
import { verifyBundle } from '../spikes/demonstrator/verification.mjs';
import { parseCanonical, unpack } from '../spikes/vault/format.mjs';
const payload = { text: 'synthetic private e\u0301 ☕ unique-draft-93817', attachments: [{ name: '../synthetic.bin', bytes: 'AP8NCg==' }] };
const input = mode => ({ payload, scope: 'test-scope', mode, supported: true });
async function fixture(t, options = {}) {
  const root = await mkdtemp(join(tmpdir(), 'provenance-integrated-test-')), egress = [];
  const session = await new DemoSession(root, async a => { egress.push(a); return 'SUBMISSION_OBSERVED'; }, options).init();
  t.after(async () => { session.close(); await rm(root, { recursive: true, force: true }); });
  return { root, session, egress };
}
test('encrypted Sealed exact-version release, portable verification and independent clean restore', async t => {
  const { root, session, egress } = await fixture(t);
  session.enroll('test-scope', 'fixture');
  const v = await session.freeze(input('Sealed'));
  assert.equal(v.state, 'PENDING_ANCHOR'); assert.equal(egress.length, 0);
  await assert.rejects(session.release({ id: v.id, scope: v.scope, currentPayload: payload, supported: true }), /confirmation/);
  const confirmed = await session.confirm({ id: v.id });
  assert.equal(confirmed.state, 'SEALED_NOT_SENT'); assert.equal(egress.length, 0);
  await assert.rejects(session.release({ id: v.id, scope: v.scope, currentPayload: { ...payload, text: 'edited' }, supported: true }), /Stale/);
  const results = await Promise.allSettled([1, 2].map(() => session.release({ id: v.id, scope: v.scope, currentPayload: payload, supported: true })));
  assert.equal(results.filter(r => r.status === 'fulfilled').length, 1); assert.equal(egress.length, 1);
  assert.deepEqual(egress[0].payload, payload);
  await session.captureVisible({ id: v.id, scope: v.scope, text: 'visible synthetic answer e\u0301' });
  const exported = session.exportDisclosure();
  assert.equal(exported.profile, 'pap-demo-export/2');
  assert.equal(exported.publicProofObjects.length, 1); assert.equal(exported.anchors.length, 1);
  assert.equal(verifyBundle(exported, exported.trust).valid, true);
  assert.equal(verifyBundle(exported, null).valid, false);
  assert.equal(verifyBundle(exported, exported.trust).anchors[0].anchor, 'FIXTURE_VERIFIED');
  await assert.rejects(session.confirm({ id: v.id }), /duplicate/);
  assert.equal(verifyBundle(session.exportDisclosure(), exported.trust).anchors.length, 1, 'duplicate confirm cannot discard accepted proof');
  const objects = parseCanonical(Buffer.from(exported.disclosure)).objects.map(o => unpack(o.bytes));
  assert.equal(objects.filter(b => b.equals(Buffer.from(payload.text))).length, 1, 'selected bytes deduplicate across release snapshots');
  assert.ok(objects.some(b => b.equals(Buffer.from([0, 255, 13, 10]))));
  assert.ok(objects.some(b => b.equals(Buffer.from('visible synthetic answer e\u0301'))));
  for (const name of await readdir(join(root, 'vault'))) assert.equal((await readFile(join(root, 'vault', name))).includes(Buffer.from(payload.text)), false);
  assert.equal((await readdir(root)).some(n => n.includes('plaintext') || n === 'release-test-journal.json'), false);
  await session.freeze({ ...input('Sealed'), payload: { text: '{"kind":"validated-confirmation","profile":"pap-demo-observation/1","recordDigest":"hostile"}', attachments: [] } });
  const backup = session.exportRecovery();
  const recoveryBaseline = session.exportDisclosure();
  const fresh = await mkdtemp(join(tmpdir(), 'provenance-clean-restore-test-'));
  t.after(() => rm(fresh, { recursive: true, force: true }));
  const { trust, ...bundle } = exported;
  await writeFile(join(fresh, 'export.json'), JSON.stringify(bundle));
  await writeFile(join(fresh, 'trust.json'), JSON.stringify(trust));
  await writeFile(join(fresh, 'recovery.json'), backup.package);
  await writeFile(join(fresh, 'secret.txt'), backup.recoveryKey, { mode: 0o600 });
  const denyNetwork = join(fresh, 'deny-network.mjs');
  await writeFile(denyNetwork, `import net from 'node:net'; import http from 'node:http'; import https from 'node:https'; import dgram from 'node:dgram'; const deny=()=>{throw Error('Network forbidden in test')}; net.Socket.prototype.connect=deny;http.request=deny;https.request=deny;dgram.createSocket=deny;globalThis.fetch=deny;`);
  const verifier = spawnSync(process.execPath, ['--import', denyNetwork, new URL('../spikes/demonstrator/verify.mjs', import.meta.url).pathname, join(fresh, 'export.json'), join(fresh, 'trust.json')], { env: {}, encoding: 'utf8' });
  assert.equal(verifier.status, 0, verifier.stderr); assert.equal(JSON.parse(verifier.stdout).valid, true);
  const restoreCode = `import {readFileSync} from 'node:fs';import {randomBytes} from 'node:crypto';import {restoreRecovery} from ${JSON.stringify(new URL('../spikes/vault/vault.mjs', import.meta.url).href)};const v=restoreRecovery(readFileSync(${JSON.stringify(join(fresh, 'recovery.json'))}),Buffer.from(readFileSync(${JSON.stringify(join(fresh, 'secret.txt'))},'utf8'),'base64url'),${JSON.stringify(join(fresh, 'restored'))},randomBytes(32));console.log(JSON.stringify({report:v.verifyAll(),disclosure:v.exportDisclosure(v.inspect().records.map(r=>r.manifest.eventId)).toString()}));v.close();`;
  const restore = spawnSync(process.execPath, ['--import', denyNetwork, '--input-type=module', '-e', restoreCode], { env: {}, encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 });
  assert.equal(restore.status, 0, restore.stderr);
  const recovered = JSON.parse(restore.stdout); assert.equal(recovered.report.snapshot, 'COMPLETE');
  assert.equal(recovered.report.latestState, 'NOT_PROVEN'); assert.equal(recovered.disclosure, recoveryBaseline.disclosure);
  assert.equal(verifyBundle({ ...bundle, disclosure: recovered.disclosure }, trust).valid, true);
  const restoredUI = session.restore(backup.package, backup.recoveryKey);
  assert.equal(restoredUI.bundle.profile, 'pap-demo-export/2');
  assert.equal(verifyBundle(restoredUI.bundle, trust).valid, true);
  assert.equal(verifyBundle(restoredUI.bundle, trust).anchors.length, 1);
  assert.equal(verifyBundle(restoredUI.bundle, null).valid, false, 'restored metadata cannot grant trust');
  assert.match(restoredUI.releaseAuthority, /^NONE/); assert.equal(restoredUI.deviceIdentity, 'FRESH');
  assert.throws(() => session.restore(backup.package, Buffer.alloc(32).toString('base64url')));
});
test('Continuous anchors after release; scoped Always Protect rejects unsupported and stale paths', async t => {
  const { session, egress } = await fixture(t); session.enroll('test-scope', 'fixture');
  const c = await session.freeze(input('Continuous'));
  await session.release({ id: c.id, scope: c.scope, currentPayload: payload, supported: true });
  assert.equal(session.status().versions[0].anchor, 'PENDING'); assert.equal(egress.length, 1);
  await session.confirm({ id: c.id }); assert.equal(session.status().versions[0].anchor, 'FIXTURE_VERIFIED');
  await assert.rejects(session.freeze({ ...input('Always Protect'), supported: false }), /UNSUPPORTED_PATH/);
  await assert.rejects(session.freeze({ ...input('Always Protect'), scope: 'other' }), /UNSUPPORTED_PATH/);
  const a = await session.freeze(input('Always Protect')); await session.confirm({ id: a.id });
  await assert.rejects(session.release({ id: a.id, scope: a.scope, currentPayload: payload, supported: false }), /UNSUPPORTED_PATH/);
  await session.release({ id: a.id, scope: a.scope, currentPayload: payload, supported: true });
  assert.equal(egress.length, 2);
  assert.throws(() => session.enroll('other', 'fixture'), /new session/);
});
test('new Algorand versions reject archived proof replay and remain pending without chain authority', async t => {
  const { session, egress } = await fixture(t);
  const root = new URL('../spikes/anchor/algorand/proof/testdata/', import.meta.url);
  const checkpoint = JSON.parse(await readFile(new URL('independent-checkpoint.json', root), 'utf8'));
  session.enroll('test-scope', 'algorand', { profile: checkpoint.profile, network: checkpoint.network, genesis: checkpoint.genesis, checkpoint });
  const v = await session.freeze(input('Sealed'));
  const request = session.anchorRequest(v.id); assert.equal(Buffer.from(request.payload, 'base64url').length, 36);
  await assert.rejects(session.confirm({ id: v.id }), /PENDING_ANCHOR/);
  await assert.rejects(session.confirm({ id: v.id, proof: await readFile(new URL('anchor-envelope.json', root), 'utf8') }), /inclusion mismatch/);
  await assert.rejects(session.release({ id: v.id, scope: v.scope, currentPayload: payload, supported: true }), /confirmation/);
  assert.equal(egress.length, 0); assert.equal(session.status().versions[0].state, 'PENDING_ANCHOR');
});
test('encrypted durable attempt survives interruption without resend', async t => {
  let crash = false;
  const { root, session, egress } = await fixture(t, { fault: phase => { if (crash && phase === 'after-egress') throw Error('simulated interruption'); } });
  session.enroll('test-scope', 'fixture'); const v = await session.freeze(input('Sealed')); await session.confirm({ id: v.id });
  crash = true;
  await assert.rejects(session.release({ id: v.id, scope: v.scope, currentPayload: payload, supported: true }), /interruption/);
  const restarted = await new ReleaseRuntime(root, async () => { throw Error('Unexpected resend'); }, undefined, { store: session.store }).init();
  const state = restarted.snapshot(); assert.equal(Object.values(state.attempts)[0].state, 'OUTCOME_UNKNOWN');
  assert.equal(state.seals[v.id].authorization, null); assert.equal(egress.length, 1);
  await assert.rejects(restarted.release({ id: v.id, scope: v.scope, currentPayload: payload, expectedDigest: v.digest }), /authorization/);
});
test('loopback API requires exact host, UI pairing and same origin', async t => {
  const root = await mkdtemp(join(tmpdir(), 'provenance-demo-http-test-'));
  const app = await startDemo(root); t.after(async () => { await app.close(); await rm(root, { recursive: true, force: true }); });
  const headers = { Origin: app.appOrigin, Authorization: `Bearer ${new URL(app.url).hash.slice(1)}` };
  for (const bad of [{}, { ...headers, Origin: 'https://hostile.invalid' }]) {
    const r = await fetch(`${app.appOrigin}/enroll`, { method: 'POST', headers: bad, body: JSON.stringify({ scope: 'test-scope', policy: 'fixture' }) }); assert.equal(r.status, 400);
  }
  const badHostStatus = await new Promise((resolve, reject) => {
    const req = request(`${app.appOrigin}/enroll`, { method: 'POST', headers: { ...headers, Host: 'hostile.invalid' } }, res => { res.resume(); resolve(res.statusCode); });
    req.on('error', reject); req.end(JSON.stringify({ scope: 'test-scope', policy: 'fixture' }));
  });
  assert.equal(badHostStatus, 400);
  const r = await fetch(`${app.appOrigin}/enroll`, { method: 'POST', headers, body: JSON.stringify({ scope: 'test-scope', policy: 'fixture' }) }); assert.equal(r.status, 200);
  assert.equal((await fetch(`${app.providerOrigin}/visible`, { method: 'POST', body: '{}' })).status, 400);
  assert.equal(app.egress.size, 0);
});
